name: "Linter Evaluator"
description: "Greet someone and record the time"
inputs:
  token:
    description: "The GitHub token to use for making API requests"
    required: true
  ignoreInlineConfig:
    description: "Whether or not inline configurations should be ignored"
    default: true
  pr_number:
    description: 'Pull Request number that dispatched the workflow'
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
